name: Deploy Single HTML to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'https://github.com/chpk/sentiment_analysis/blob/main/network_with_communities.html'  # Ensures the workflow runs only when this file changes
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload HTML File
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'https://github.com/chpk/sentiment_analysis/blob/main/network_with_communities.html'  # Specify only the HTML file

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
